services:
  geocoder:
    image: traccar-geocoder-geocoder:latest
    environment:
      - PBF_URLS=https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      - GEOCODER_NO_AUTH=true
    ports:
      - "3000:3000"
    volumes:
      - geocoder-data:/data

volumes:
  geocoder-data:
